acls:
-   acls:
    -   aces:
        -   remark: googleDNS
            sequence: 10
        -   destination:
                any: true
            grant: permit
            protocol: ipv4
            sequence: 20
            source:
                host: 8.8.8.8
        name: ACL1
    -   aces:
        -   remark: Do not allow user1 to telnet out
            sequence: 10
        -   destination:
                any: true
                port_protocol:
                    eq: telnet
            grant: deny
            protocol: tcp
            sequence: 20
            source:
                address: 0.0.2.88
                wildcard_bits: 255.255.0.0
        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 30
            source:
                any: true
        name: telnetting
    afi: ipv4
-   acls:
    -   aces:
        -   destination:
                any: true
            grant: permit
            protocol: ipv6
            sequence: 10
            source:
                prefix: 3333:1:2:3::/64
        -   destination:
                any: true
            grant: permit
            protocol: ipv6
            sequence: 20
            source:
                prefix: 4444:1:2:3::/64
        -   destination:
                any: true
            grant: permit
            protocol: ipv6
            sequence: 30
            source:
                prefix: 5555:1:2:3::/64
        -   remark: Block BGP traffic from a given host
            sequence: 39
        -   destination:
                host: 7777:1:2:3::20
                port_protocol:
                    range:
                        end: '1400'
                        start: '1300'
            grant: deny
            protocol: tcp
            sequence: 40
            source:
                host: 6666:1:2:3::10
                port_protocol:
                    eq: bgp
        name: Internetfilter
    afi: ipv6
