---
- name: IOS config acl playbook validate
  hosts: devnetXe
  gather_facts: no
  tasks:
  - name: grab IOS facts
    cisco.ios.ios_facts:
      gather_subset: min
      gather_network_resources: acls

  - name: Dump configuration of ACLs
    copy:
      content: "{{ ansible_network_resources | to_nice_yaml }}"
      dest: "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}.yaml"

  - name: Ensure that the acl information is accurate.
    cisco.ios.ios_acls:
      config: "{{ ansible_network_resources['acls'] }}"
      state: merged
    register: result

  - name: Ensure config did not change.
    assert:
      that: not result.changed
