---
- name: Junos facts playbook
  hosts: junos
  gather_facts: no
  tasks:
  - name: Gather legacy and resource facts
    junipernetworks.junos.junos_facts:
      gather_subset: all
      gather_network_resources: all

  - name: collect default set of facts and configuration
    junipernetworks.junos.junos_facts:
      gather_subset: config