-
  hosts: brownfield
  gather_facts: no
  tasks:

    - name: ACL Management IOS-XR Network_Management2
      cisco.iosxr.iosxr_config:
        lines:
          - "10 permit ipv6 3333:1:2:3::/64 any"
          - "20 permit ipv6 4444:1:2:3::/64 any"
          - "30 permit ipv6 5555:1:2:3::/64 any"
          - "39 remark Block BGP traffic from a given host"
          - "40 deny tcp host 6666:1:2:3::10 eq bgp host 7777:1:2:3::20 range 1300 1400"
        parents:
          - "ipv6 access-list Network_Management2"

    - name: ACL Management IOS-XR Network_Management1
      cisco.iosxr.iosxr_config:
        lines:
          - "10 permit ipv4 192.168.10.0 0.0.0.255 any"
          - "20 permit ipv4 192.168.20.0 0.0.0.255 any"
          - "30 permit ipv4 192.168.30.0 0.0.0.255 any"
          - "40 permit ipv4 192.168.40.0 0.0.0.255 any"
        parents:
          - "ipv4 access-list Network_Management1"

    - name: ACL Management IOS-XR GoogleDNS1
      cisco.iosxr.iosxr_config:
        lines:
          - "10 remark googleDNS"
          - "20 permit ipv4 host 8.8.8.8 any"
        parents:
          - "ipv4 access-list GoogleDNS1"

    - name: GoogleDNS1 for Gig0/0/0/0
      cisco.iosxr.iosxr_config:
        lines:
          - "ipv4 access-group GoogleDNS1 ingress"
        parents:
          - "interface GigabitEthernet0/0/0/0"

    - name: Network_Management2 for Gig0/0/0/1
      cisco.iosxr.iosxr_config:
        lines:
          - "ipv6 access-group Network_Management2 ingress"
        parents:
          - "interface GigabitEthernet0/0/0/1"