-
  hosts: brownfield
  gather_facts: no
  tasks:
    - name: IOSXR - Show ACLs and Interface details from brownfield device
      cisco.iosxr.iosxr_command:
        commands:
          - "show access-lists afi-all"
          - "show running-config interface"
      register: result

    - name: IOSXR - ACLs on brownfield device
      debug:
        var: result.stdout_lines
