---
- hosts: clearslate
  gather_facts: no
  vars_files:
    - "vars/iosxr.yaml"
  tasks:
    - name: IOSXR - Configure ACLs on a clear slate device
      cisco.iosxr.iosxr_acls:
        config: "{{ acls }}"
        state: overridden
      when: ansible_network_os == "cisco.iosxr.iosxr"

    - name: IOSXR - Configure ACL_Interfaces on clear slate device
      cisco.iosxr.iosxr_acl_interfaces:
        config: "{{ acl_interfaces }}"
        state: overridden
      when: ansible_network_os == "cisco.iosxr.iosxr"

    - name: IOSXR - Show ACLs and Interface details from clear slate device
      cisco.iosxr.iosxr_command:
        commands:
          - "show access-lists afi-all"
          - "show running-config interface"
      register: result

    - name: IOSXR - ACLs and Interface on clear slate device
      debug:
        var: result.stdout_lines
