---
- hosts: brownfield
  gather_facts: no
  vars_files:
    - "vars/iosxr.yaml"
  tasks:
    - name: IOSXR - Check for drift
      cisco.iosxr.iosxr_acls:
        config: "{{ acls }}"
        state: overridden
      when: ansible_network_os == "cisco.iosxr.iosxr"
      register: result_check
      check_mode: true

    - name: IOSXR - Configure ACLs back to previous state
      cisco.iosxr.iosxr_acls:
        config: "{{ acls }}"
        state: overridden
      when: ansible_network_os == "cisco.iosxr.iosxr" and result_check.changed == True
      register: result

    - name: IOSXR - Commands fired for respective device
      debug:
        var: result["commands"]
      when: ansible_network_os == "cisco.iosxr.iosxr"

    - name: IOSXR - Configuration restored successfully
      debug:
        msg: Configuration drift detected and resolved on {{ inventory_hostname }}
      when: result.changed == True
