---
- hosts: all
  gather_facts: no
  vars_files:
    - "vars/iosxr.yaml"
    - "vars/junos.yaml"
  tasks:
    - name: IOSXR - Update ACLs
      cisco.iosxr.iosxr_acls:
        config: "{{ acls }}"
        state: replaced
      register: iosxr_result
      when: ansible_network_os == "cisco.iosxr.iosxr"

    - name: JUNOS - Update ACLs
      junipernetworks.junos.junos_acls:
        config: "{{ junos_acls }}"
        state: replaced
      register: junos_result
      when: ansible_network_os == "junipernetworks.junos.junos"

    - name: IOSXR - Commands fired for respective device
      debug:
        var: iosxr_result["commands"]
      when: ansible_network_os == "cisco.iosxr.iosxr"

    - name: JUNOS - Commands fired for respective device
      debug:
        var: junos_result["xml"]
      when: ansible_network_os == "junipernetworks.junos.junos"
