---
- hosts: all
  gather_facts: no
  vars_files:
    - "vars/iosxr.yaml"
    - "vars/junos.yaml"
  tasks:
    - name: IOSXR - Update ACLs
      iosxr_acls:
        config: "{{ acls }}"
        state: replaced
      when: ansible_network_os == "cisco.iosxr.iosxr"

    - name: JUNOS - Update ACLs
      junos_acls:
        config: "{{ junos_acls }}"
        state: replaced
      when: ansible_network_os == "junipernetworks.junos.junos"

    - cisco.iosxr.iosxr_command:
        commands:
          - "show access-lists Network_Management1"
      register: iosxr_res
      when: ansible_network_os == "cisco.iosxr.iosxr"

    - name: IOSXR - Show updated IOSXR ACLs from device
      debug:
        var: iosxr_res.stdout_lines
      when: ansible_network_os == "cisco.iosxr.iosxr"

    - junipernetworks.junos.junos_command:
        commands:
          - "show configuration firewall family inet filter from-cisco"
      register: junos_res
      when: ansible_network_os == "junipernetworks.junos.junos"

    - name: JUNOS - Show updated JUNOS ACLs from device
      debug:
        var: junos_res.stdout_lines
      when: ansible_network_os == "junipernetworks.junos.junos"