---
- hosts: iosxr
  gather_facts: no
  vars_files:
    - "vars/iosxr.yaml"
  tasks:
    - name: "Iosxr - Configure ACLS"
      iosxr_acls:
        config: "{{ acls }}"
        state: overridden
      when: ansible_network_os == "cisco.iosxr.iosxr"
      register: result

    - name: "Checking for config drift"
      debug:
        # var: result
        msg: Configuration drift detected {{ inventory_hostname }}
      when: result.changed == True
